name: webapi_docker
services:
  webapi_docker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "sql-container"
    environment:
      MSSQL_SA_PASSWORD: "SecretPassword_1"
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"